### ISSUE TITLE
How about Compact filed device？

### ISSUE THREAD

**Issue by frankgp** [rtlabs-com/p-net#443]
Now p-net sample is module type field device. 
Does the p-net device stack suppot compact type field device？
such as the IO data were put into slot 0？

**Comment by pyhys** [comment]
A compact field device is a device where the modules are fixed in their slots.
This is given in the GSDML file as `FixedInSlots`, as described on https://rt-labs.com/docs/p-net/creating_gsdml_files.html

However the slot numbers will be 1 and higher, as slot 0 is reserved for the DAP module (has information on the device itself).

Closing this issue. Please reopen if required.
