### ISSUE TITLE
 Does not check validity of incoming gateway

### ISSUE THREAD

**Issue by pyhys** [rtlabs-com/p-net#79]
Found with Automated RT Tester DCP_Router

**Comment by pyhys** [comment]
See discussion in #51

**Comment by pyhys** [comment]
Use skeleton from #96

**Comment by atomic-3dpenguin** [comment]
This issue is not addressed.  It always returns PF_DCP_BLOCK_ERROR_SUBOPTION_NOT_SET when trying to set the IP Suite

Please see the attached to address the issue:
![pnet_ip_suite_change_1](https://user-images.githubusercontent.com/66037099/84449247-b5026800-ac01-11ea-89ea-a68c0afd62fa.png)
![pnet_ip_suite_change_2](https://user-images.githubusercontent.com/66037099/84449249-b59afe80-ac01-11ea-8547-865a46b4e990.png)
